export const metadata = {
	title: "Home page",
	description: "Generated by create next app",
};

/** Add your relevant code here for the issue to reproduce */
export default function Home() {
	return null;
}
